### ISSUE TITLE
Water preset?

### ISSUE THREAD

**Issue by dandv** [schalkt/tgen#1]
I'm trying to build a seamlessly scrolling background to simulate a river flowing from right to left. What I've got working is in [this Codepen](http://codepen.io/dandv/pen/aOqaMZ), but I suspect a solid water-like background would give a much better illusion of motion. How could I use tgen to achieve that?

**Comment by schalkt** [comment]
Try this new water preset: [http://seamless-texture.com/generator/?preset=water](http://seamless-texture.com/generator/?preset=water)
Currently under development, so I think you must click 30 times, that get an acceptable texture. :)

**Comment by dandv** [comment]
Looks pretty fluid :) In the meantime I went with [some predefined textures](http://codepen.io/dandv/pen/QbmbrW), which confirmed the illusion of motion hunch.
