### ISSUE TITLE
Quasi-reproducibility of textures

### ISSUE THREAD

**Issue by dandv** [schalkt/tgen#2]
I'm new to texture generation, so pardon my ignorance. While running the same code in the README several times, one of the generated textures seemed like a good fit for my project (#1). Is there an introspection API call to get some sort of ID of that texture, that would make it possible to reproduce it in the future, or at least within some parameters, e.g. dominant color?

**Comment by schalkt** [comment]
Yes, you can get the randomly generated texture parameters by the params() function:
```
var texture = tgen(256).waves();
var params = texture.params();
```

It's ugly, but you can change the parameters and render with the new values:

```
// params.items[<itemnumber>][0] = <layer-number>
// params.items[<itemnumber>][1] = <layer-effect>
// params.items[<itemnumber>][2] = <layer-effect-parameters>

params.items[0][1] = 'spheres'; // change layer effect
params.items[0][2].rgba = [255,50,10,0.85]; // change layer effect color
var texture2 = tgen().render(params);
```

We have new effects and presets. (clouds, color clouds)
Test it :)
