### ISSUE TITLE
Mul not initialised in generator function

### ISSUE THREAD

**Issue by optimus007** [schalkt/tgen#23]
https://github.com/schalkt/tgen/blob/712368fe71a7ce3fca6350af2e72afbb59b74cbf/src/tgen-generator.js#L306-L322

`tgen-generator.js:316 Uncaught ReferenceError: mul is not defined`

**Comment by schalkt** [comment]
I will fix it soon.
Thanks!

**Comment by schalkt** [comment]
Ah, it's already fixed a long time ago :)
What version do you have?

**Comment by optimus007** [comment]
`"seamless-texture-generator": "^1.4.5"`

installed it today via npm

and i've imported it as `import * as tgen from 'seamless-texture-generator/src/tgen-base'`

**Comment by schalkt** [comment]
I found and fixed :)
And I also found some other errors too.
So, big thanks :)
Check the latest version (1.4.9)

**Comment by optimus007** [comment]
another syntax error while making the `generator.render(params)` from examples

`tgen-generator.js:1246 Uncaught ReferenceError: effect is not defined`

https://github.com/schalkt/tgen/blob/3e09eb9d96b44275f1f7100d1a1b6d348364050d/src/tgen-generator.js#L1245-L1265

**Comment by schalkt** [comment]
Oh, I think the webpack is do something why these errors does not appear while using the compressed files in dist folder.
I will fix it this weekend. Thanks!

**Comment by schalkt** [comment]
I think it will be good now :)
I installed eslint and checked/fixed all issues and created index.js for the import.
Import example:
```import tgen from 'seamless-texture-generator';```

Check please the **new 1.4.10 version**, thanks
