### ISSUE TITLE
How do I get this to work offline?

### ISSUE THREAD

**Issue by LinuxBeaver** [schalkt/tgen#25]
I installed the production version with NPM but don't know how to launch it. Much appreciated if this can be resolved.

**Comment by schalkt** [comment]
It depends what do you want to see :)
For the demo website just start the ./demo/index.html
But if you want to include the generator into your project see this files:
- https://github.com/schalkt/tgen/blob/master/test/import/test.js
- https://github.com/schalkt/tgen/blob/master/test/test.js

**Comment by LinuxBeaver** [comment]
Index.html works offline using the Midori browser but not Firefox.  I have not tested Chromium.

**Comment by schalkt** [comment]
Works for me in Firefox (version 102.0.1) on Windows 10, and I don't see error messages. 
Please check the console log of browser. Thanks!
