### ISSUE TITLE
PIXI

### ISSUE THREAD

**Issue by TheRealTR** [schalkt/tgen#29]
I'd like to use tgen textures as sprite textures in PIXI. Possible?

**Comment by schalkt** [comment]
Good question :)
Yes, it is possible.
Example:

```javascript
    const generator = tgen.init(256, 256);
    const texture = generator.render({
      preset: {
        name: "waves-cool",
        seed: null,
      },
    });

    const sprite = PIXI.Sprite.from(texture.toCanvas());
    const app = new PIXI.Application({ background: '#000' });

    sprite.anchor.set(0.5);
    sprite.x = app.screen.width / 2;
    sprite.y = app.screen.height / 2;
    app.stage.addChild(sprite);
    app.ticker.add((delta) => {
      sprite.rotation += 0.01 * delta;
    });

    document.body.appendChild(app.view);
```

**Comment by TheRealTR** [comment]
I think I'm almost there...

My implementation uses a lot of objects. I'm writing one that would create a tgen canvas and return it to be applied to any number of sprites. The refresh method can be called on the object to regenerate the canvas.

function newseamless(){
	const me ={};
	me.gen = tgen.init(512, 512);
	me.params = {
		preset: {
			name: "waves-cool",
			seed: null,
		}
	}
	me.refresh = function(){
		me.canvas = me.gen.render(me.params).toCanvas();
	}
	me.refresh();
	return(me);	
}

me.canvas would be applied to the sprite. I'm getting an 'undefined is not an object' from PIXI when I try to use the canvas. Am I missing a step?

**Comment by schalkt** [comment]
When you use presets, you have to load another js file :  [tgen-with-presets.min.js](https://github.com/schalkt/tgen/blob/master/dist/tgen-with-presets.min.js)

**Comment by schalkt** [comment]
> 'me.canvas' would be applied to the sprite. I'm getting an **undefined is not an object (evaluating 'm.presets[o].items')** from PIXI when I try to use the canvas. Am I missing a step?

Your code looks good, just change the tgen.min.js file to tgen-with-presets.min.js and there will be no errors. :)
