### ISSUE TITLE
console.log events

### ISSUE THREAD

**Issue by travisapple** [schalkt/tgen#3]
First off, I have no idea why this project isn't more popular. The results I'm getting are amazing. Small issue:

I do js debugging through the console and the performance console.log() lines triggered by events in tgen-events.js are a little frustrating to wade through after a while. I'm putting this to block them:

	tgen.event('beforeEffect', 'save start time', function ($g, effect) {});
	tgen.event('afterEffect', 'log', function ($g, effect) {});
	tgen.event('beforeRender', 'log', function ($g, params) {});
	tgen.event('afterRender', 'log', function ($g, params) {});

Any chance you can add something where you turn on the events only when you need to see them?

Thank you!

**Comment by travisapple** [comment]
Also, I'm pulling color data directly sometimes and don't want to run it through a canvas. It wasn't obvious right away that you need to pull this like:

generator.render(params);
var unclamped = generator.texture.data;

and then clamp it to 0-255. Maybe a something like calling generator.render(params).rawData() would return a Uint8ClampedArray with rgba color data.

Thanks again.

**Comment by schalkt** [comment]
Thanks for the feedback. :) Very useful.
I will do these features within a few days.

**Comment by schalkt** [comment]
Done. :)
Please **update** your tgen version to **v1.0.2**

**Log**
- debug log disabled by default
- adjustable in params: ```{ "debug": true, "width":  256, "height": 256, ...}```

**Get raw image data**
- ```var rawData = generator.texture.export('clamped'); ```

**Comment by schalkt** [comment]
Hi @travisapple,

What's up? :)
Does it work?

**Comment by travisapple** [comment]
Just getting back into the office... sorry for the delay.

THANK YOU for your time here.

I tested that the console.log calls are gone and that there's a nice "'debug': true," in the params. That should make it convenient for people to test speed for webgl texture generation (me included). 

generator.texture.export('clamped') was tested and is working correctly. For me, it's used to simulate natural wind patterns across a grass field and looking great.

Thanks again for your effort here and in this entire project.

**Comment by schalkt** [comment]
Can you show a screenshot or something, it sounds really interesting? :)
