### ISSUE TITLE
remove randomness

### ISSUE THREAD

**Issue by pjebs** [schalkt/tgen#4]
Is there any way to remove randomization seed for testing purposes.

**Comment by schalkt** [comment]
Yes, you must set the exact values in parameters.
The example below always rendering a same image.
But if the **xsines** changed to [5,10] the system randomize the value between 5 and 10 and you get a different image. If you add the **seed : 2** parameter, the xsines parameter will be always 6.

```javascript
{
  "width": 256,
  "height": 256,
  "normalize": "limitless",
  "items": [
    [
      0, "waves", {
        "blend": "opacity",
        "rgba": [
          15,
          35,
          195,
          255
        ],
        "level": 50,
        "xsines": 5,
        "ysines": 10
      }
    ]
  ]
}
```
