### ISSUE TITLE
Seamless Texture From Image

### ISSUE THREAD

**Issue by glenngartner** [schalkt/tgen#5]
Thanks for the great work. Awesome tool. Can we currently create a seamless texture using a source image? From a URL, canvas, or otherwise?

**Comment by schalkt** [comment]
Thanks!
I thought about doing this, but it's not that simple 😄 
So currently there's no such feature.

**Comment by glenngartner** [comment]
Thanks, you're right. It's not so simple. I'll begin writing my own.
